### ISSUE TITLE
Add token revocation

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_cli#176]
Incl. logout.

**Comment by alneberg** [comment]
What does this mean? The JWTs can't be revoked as I understand it since they are not tracked on the server. One can currently delete the token stored locally, but besides that, we need to disable the user from all logins until all possible tokens have expired. But if this issue is from the 332 document I think having short lived tokens are enough?

**Comment by inaod568** [comment]
I believe this is exactly what you have already implemented with the logout. So I'll close this.
