### ISSUE TITLE
How to resume file transfer after being interrupted

### ISSUE THREAD

**Issue by Sameerpython** [ScilifelabDataCentre/dds_cli#637]
Hi,
Is there a way to resume the partially transferred file using dds? 
And I also see Warnings such as :
WARNING  Decryption failed.                                                                                                 
WARNING  Checksum verification failed. File compromised.                                                                    
WARNING  download_and_verify failed: Checksum verification failed. File compromised. 

In such a case, what do I do?

Thanks!

**Comment by i-oden** [comment]
Hi, 
Unfortunately there's no way of resuming a download. We may add this later on but atm you'll need to redo it. 
Regarding the error messages, these could be due to a number of different things, usually it's that there's not enough space where you're downloading or there's no executable permission.

To figure this out, could you do the following: 
1. Run the same command again, but add the `--log-file` option. Note that you need to have this just after `dds`, and not at the end of the command. It should be this structure: `dds --log-file [log file] data get [rest of command]`
2. Send this to the unit that is delivering your data and explain your problem.
3. If they do not know how to handle this, they can CC our support email and we can help out.

Thanks!

**Comment by Sameerpython** [comment]
> Hi again, It's not possible to use rsync unfortunately, only the dds-cli. Partly because the encryption/decryption/compression/decompression is handled by the client.

Ok. Thank you for the clarification.
