### ISSUE TITLE
Fix Windows icon compatibility 

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_cli#93]
The CLI only displays small question mark symbols instead of up/down/lock/warning symbols etc.

**Comment by inaod568** [comment]
The symbols don't work in legacy windows but works in other terminals. There's a `rich.console.detect_legacy_windows()` method that we can use and then change the formatting, haven't found how to display symbols etc in legacy windows yet though.

**Comment by MatthiasZepper** [comment]
I have now finished an extensive testing across various platforms (screenshots available if needed) and the take home message is quite straightforward: 

The terminal **must support Unicode UTF-8** encoding and the font chosen by the user for the terminal emulator **must support the symbols**. If the terminal is set to the wrong encoding (which can be forcefully done also on Mac or Linux) then boxes or rather arbitraty letters are shown in place. If the font has no good support for the symbols they are shown as monochromatic symbols that are hardly identifiable.

| OS            | Shell      | Emulator                          | Result                            |
|---------------|------------|-----------------------------------|-----------------------------------|
| Windows 8     | cmd        | cmd                               | not working - boxes               |
| Windows 8     | PowerShell | PowerShell                        | not working - boxes               |
| Windows 8     | PowerShell | PowerShell for VS                 | not working - boxes               |
| Windows 8     | PowerShell | PowerShell ISE                    | Python crashes                    |
| Windows 8     | PowerShell | Visual Studio Code Terminal       | works                             |
| Windows 8     | PowerShell | Terminal App                      | works                             |
| macOS BigSur  | zsh        | iTerm2                            | works                             |
| macOS BigSur  | zsh        | iTerm2  set to ISO-8859-2 | not working - letter replacements |
| macOS BigSur  | zsh        | iTerm2  set to CP-1252   | not working - letter replacements |
| macOS BigSur  | zsh        | Visual Studio Code Terminal       | works                             |
| macOS BigSur  | zsh        | PyCharm Terminal                  | works                             |
| Linux Mint 19 | bash       | GnomeTerminal 3                   | works                             |
| Linux Mint 19 | bash       | GnomeTerminal 3 set to ISO-8859-2 | not working - letter replacements |
| LinuxMint 19  | bash       | GenomeTerminal 3 set to CP-1252   | not working - letter replacements |
| Linux Mint 19 | bash       | Guake                             | works                             |

The terminal app is available in Windows 8 and newer and can be installed in older systems. On macOS and Linux all tested emulators have UTF-8 or even UTF-9 as default setting and thus will support and display the symbols and only failed when forcefully set to the wrong encoding. 

We should discuss if the support of really long outdated systems like WinXP is really required? In that case it might be reasonabe to switch to textual replacements and write the status as _get, put, dcrpt_ ...

**Comment by ewels** [comment]
Wow, comprehensive @MatthiasZepper ! 🙇🏻 

For anything using `rich` for output, I'm a little surprised as the docs say that it supports windows: https://rich.readthedocs.io/en/stable/introduction.html#requirements - but maybe not these cases / systems?

Personally I think that going back as far as XP etc is a little excessive. Assuming that the cli doesn't crash, I guess it should still work in non-interactive modes (eg. download) with command line flags in these extreme edge cases which should be enough..? But also find to just list the requirements I think.

**Comment by ewels** [comment]
Also to add some more complexity - I assume that the majority of users will be downloading to uppmax. So for example, running on Rackham (linux) via ssh to local windows. My guess is that the same character issues will present in that case though..?

**Comment by inaod568** [comment]
Thank you for this! 

We should definitely discuss this, but the reason for even looking into this in the first place was that two (could've been more but I remember 2) people involved in the testing during spring/summer complained about it, and yes (@ewels) I believe they were using UPPMAX

**Comment by MatthiasZepper** [comment]
> Also to add some more complexity - I assume that the majority of users will be downloading to uppmax. So for example, running on Rackham (linux) via ssh to local windows. My guess is that the same character issues will present in that case though..?

Valid concern. I recalled that PuTTy was the ssh-Client which I used back on Windows XP and [apparently it is still the prime choice nowadays](https://www.makeuseof.com/tag/4-easy-ways-to-use-ssh-in-windows/). According to [PuTTys documentation UTF-8 is the default setting](https://tartarus.org/~simon/putty-snapshots/htmldoc/Chapter4.html#config-charset) and was introduced in PuTTy 0.62 released on 2011-12-10. I also do not recall that I ever had an encoding issue in PuTTy connecting to the HPC cluster in Münster. 

I could find more recent questions asking for help regarding mangled symbols in PuTTy [[1](https://serverfault.com/questions/378352/can-putty-be-configured-to-display-the-following-utf-8-characters)],[[2](https://serverfault.com/questions/1048795/putty-not-showing-some-utf-8-characters)] , but they were both attributable to lacking font support for those symbols. I have no idea if it is possible to programmatically read-out the encoding and font of the terminal, but I will check in the documentation of rich.

I have already discussed with Ina that we will provide a simple alternative for the progress bars, but not over-complicate things. For those users who still run into issues, I will write a short summary of possible causes and solutions to be included into a Troubleshooting guide for the DDS.

**Comment by MatthiasZepper** [comment]
Just to give an update on the issue: Ina suggested to add another if/else statement to the `text_handler.py` that will branch into a text only version for older terminals. We agreed that it is desirable to have a means of auto-detection instead of e.g. a command-line parameter to switch between the emoji and text-only status. 

Ina had suggested to use `rich.console.detect_legacy_windows`, both a method and a flag. Hence, I tried to find out what exactly this method detects. The [rich source code](https://rich.readthedocs.io/en/stable/_modules/rich/console.html#detect_legacy_windows) shows that it wraps [colorama](https://github.com/tartley/colorama). Thus, I spent the last few hours taking the deep dive into the internal workings of terminals to understand how formatting output works. 

To achieve the display colors and character styles in terminals and emulators, as well as other functionality such clearing screens, moving cursors and setting title bars, [ANSI-escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code) are used. Technically, these are just sequences of bytes and are embedded within the bytes of the text as if they were regular letters. However, instead of just being displayed, they convey a command or action that is interpreted by the terminal. Since they were introduced in the UNIX world in the late 1970ies, [most systems except Windows NT supports them](https://mixmastamyk.bitbucket.io/console/why.html#background). From Windows 7 on [the new terminal app reintroduced the support for them](https://github.com/microsoft/terminal#the-windows-console-host), so that [ANSI-escape codes need to be converted to the Microsoft-specific terminal calls](https://github.com/tartley/colorama#usage) for all systems using prior to Windows7 and later than Windows95.

All Python packages that provide high level means to style terminal output, such as [colorama](https://github.com/tartley/colorama), [blessed](https://pypi.org/project/blessed/) or [blessings](https://pypi.org/project/blessings/) however do not seem to directly perform the format string to bytecode conversion themselves, but either use [pyterminfo](https://github.com/zachariahreed/pyterminfo) or one of the several wrappers of the [curses library](https://docs.python.org/3/library/curses.html):

| High Level | Low Level |
|------------|-----------|
| <img src="https://raw.githubusercontent.com/zachariahreed/pyterminfo/gh-pages/TERMINFO-set_a_foreground.png" width=375> | <img src="https://raw.githubusercontent.com/zachariahreed/pyterminfo/gh-pages/BYTECODE-set_a_foreground.png" width=375> | 

Support for the conversion to Windows is apparently either provided by [Jinxed](https://jinxed.readthedocs.io/en/stable/api.html), [Windows Curses](https://pypi.org/project/windows-curses/) or [Teletype](https://pypi.org/project/teletype/).

However, all of the documentation that I have read today only dealt with formatting text on the terminal and printing it styled, with color or perform positioning on the terminal. None mentioned symbols or emojis specifically. Hence, all of this Windows legacy terminal detection might actually lead us nowhere, because it just addresses the ANSI-escape codes and their mapping to the Windows bindings respectively their bytecode conversion for all systems. 

The problem here is, that the remainder of the text is "just displayed" after the ANSI-escape codes have been stripped and processed in an O-specific and terminal-specific manner. Since our emojis are regular unicode characters, they should be part of the "payload". So the key here is to determine if the current terminal (emulator) is set to support UTF-8 and not how well it supports the ANSI-escape codes or how many lines it's viewport comprises - stuff that the curses library typically "knows" from querying a large database that collects the properties of thousands of terminals and terminal emulators. 

Unfortunately, I have not yet figured out if there is a generic "one size fits all" approach to determine the encoding a terminal is set to. One can print this setting on most shells, so it should be possible to somehow get this response into Python, but I would like to avoid writing something like that myself... I will continue working on that tomorrow.

**Comment by ewels** [comment]
Guys, whilst this is very nice, surely we're talking about a tiny number of users here? I would have thought that there must be higher priorities - it's ok to tell people to use a different terminal if necessary.
